# apiVersion: v1
# kind: ConfigMap

# metadata:
#   name: {{ template "chart.fullname" . }}
#   labels:
#     app: {{ template "chart.name" . }}
#     chart: {{ template "chart.name" . }}-{{ .Chart.Version }}
#     heritage: {{ .Release.Service }}
#     release: {{ .Release.Name }}
#     version: {{ .Chart.AppVersion | quote }}

# data:
#   {{- range $key, $value := .Values.config }}
#   {{ $key }}: |-
#     {{ $value | indent 2 }}
#   {{- end }}
