apiVersion: v1
kind: Service

metadata:
  name: {{ template "chart.fullname" . }}-public
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ template "chart.name" . }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    version: {{ .Chart.AppVersion | quote }}

spec:
  type: NodePort
  selector:
    app: {{ template "chart.name" . }}

  ports:

  - name: p2p
    protocol: UDP
    port: {{ .Values.ports.p2p }}
    targetPort: 8336

  - name: p2pMaster
    protocol: UDP
    port: {{ .Values.ports.p2pMaster }}
    targetPort: 8340

  {{ range $i, $e := until (int .Values.ports.workers) }}
  - name: worker1_p2p
    protocol: UDP
    port: {{ 50000 | add $i }}
    targetPort: 50000

  - name: worker1_stream
    protocol: UDP
    port: {{ 60000 | add $i }}
    targetPort: 60000
  {{ end }}
  