apiVersion: v1
kind: Service

metadata:
  name: {{ template "chart.fullname" . }}-public
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ template "chart.name" . }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    version: {{ .Chart.AppVersion | quote }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  
spec:
  type: LoadBalancer
  selector:
    app: {{ template "chart.name" . }}

  ports:

  - name: p2p
    protocol: UDP
    port: {{ .Values.ports.p2p }}
    targetPort: 8336

  - name: p2p-master
    protocol: UDP
    port: {{ .Values.ports.p2pMaster }}
    targetPort: 8340

  {{ range $i, $e := until (int .Values.ports.workers) }}
  - name: worker{{ $i }}-p2p
    protocol: UDP
    port: {{ add 50000 $i }}
    targetPort: {{ add 50000 $i }}

  - name: worker{{ $i }}-stream
    protocol: UDP
    port: {{ add 60000 $i }}
    targetPort: {{ add 60000 $i }}
  {{ end }}
  